# NUMPY

In [ ]:
import numpy as np

## Creating np Arrays

In [ ]:
arr = np.arange(5)

In [ ]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.array([0.0, 2, 4, 6, 8])

In [ ]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [ ]:
arr

array([0., 2., 4., 6., 8.])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6]
])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.size

12

In [ ]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
1729 * np.ones((2, 3, 4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [ ]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.13890333,  0.27855673,  0.21005722],
       [-1.62569229, -0.13162848, -0.95659027]])

In [ ]:
np.random.rand(2, 3)

array([[0.3162607 , 0.64561188, 0.15635594],
       [0.8700201 , 0.24331023, 0.6859318 ]])

In [ ]:
np.random.rand(10, 1)

array([[0.50711323],
       [0.64183329],
       [0.19184264],
       [0.04014946],
       [0.96683666],
       [0.85560495],
       [0.69896133],
       [0.12290663],
       [0.75425615],
       [0.47505099]])

## Numpy Operations

In [ ]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [ ]:
arr1

array([[0.22962077, 0.51507481, 0.73337689, 0.0732048 ],
       [0.84785699, 0.1344861 , 0.41097148, 0.79916757],
       [0.29367862, 0.72556205, 0.33804899, 0.70370708]])

In [ ]:
arr2

array([[0.98809128, 0.08682292, 0.89697772, 0.51651258],
       [0.7306907 , 0.27225471, 0.56516733, 0.84888119],
       [0.02934795, 0.65008809, 0.38822344, 0.74712479]])

In [ ]:
arr1 + arr2

array([[1.21771204, 0.60189773, 1.63035461, 0.58971738],
       [1.57854769, 0.40674081, 0.97613881, 1.64804876],
       [0.32302657, 1.37565014, 0.72627243, 1.45083187]])

In [ ]:
arr1 - arr2

array([[-0.75847051,  0.4282519 , -0.16360083, -0.44330778],
       [ 0.1171663 , -0.13776861, -0.15419585, -0.04971363],
       [ 0.26433067,  0.07547396, -0.05017445, -0.04341771]])

In [ ]:
arr1 * arr2

array([[0.22688627, 0.0447203 , 0.65782273, 0.0378112 ],
       [0.61952122, 0.03661447, 0.23226765, 0.67839832],
       [0.00861886, 0.47167925, 0.13123854, 0.525757  ]])

In [ ]:
arr1 / arr2

array([[ 0.23238821,  5.93247539,  0.81760881,  0.14172897],
       [ 1.16035006,  0.49397162,  0.72716779,  0.9414363 ],
       [10.0067855 ,  1.11609804,  0.87075884,  0.94188694]])

In [ ]:
np.exp(arr1)

array([[1.2581228 , 1.67376371, 2.08209977, 1.07595087],
       [2.33463834, 1.14394876, 1.50828234, 2.22368909],
       [1.34135275, 2.06589191, 1.4022092 , 2.0212317 ]])

In [ ]:
np.log(np.exp(arr1))

array([[0.22962077, 0.51507481, 0.73337689, 0.0732048 ],
       [0.84785699, 0.1344861 , 0.41097148, 0.79916757],
       [0.29367862, 0.72556205, 0.33804899, 0.70370708]])

In [ ]:
np.sin(arr1)

array([[0.22760826, 0.49259996, 0.6693822 , 0.07313943],
       [0.74986433, 0.13408107, 0.3995001 , 0.71677588],
       [0.2894753 , 0.66355603, 0.33164714, 0.64704858]])

In [ ]:
np.cos(arr1)

array([[0.97375278, 0.87025587, 0.74291821, 0.99732173],
       [0.66159163, 0.99097037, 0.91673315, 0.69730362],
       [0.95718548, 0.74812659, 0.94340351, 0.76244877]])

In [ ]:
np.sqrt(arr1)

array([[0.47918761, 0.71768713, 0.85637427, 0.27056385],
       [0.9207915 , 0.36672347, 0.64107057, 0.89396173],
       [0.54192123, 0.8517993 , 0.58141981, 0.8388725 ]])

In [ ]:
arr_inv

array([[ 4.35500683,  1.94146554,  1.36355538, 13.66030672],
       [ 1.17944418,  7.43571259,  2.43325888,  1.25130203],
       [ 3.40508274,  1.37824187,  2.9581511 ,  1.42104581]])

In [ ]:
arr1 = np.zeros((3, 5))

## Stats with NumPy

In [ ]:
arr = np.random.rand(10000000,)

In [ ]:
np.mean(arr)

0.4999167853382263

In [ ]:
np.var(arr)

0.0833092842068402

In [ ]:
np.std(arr)

0.28863347728016614

In [ ]:
np.median(arr)

0.4998715565990975

In [ ]:
np.percentile(arr, 50)

0.4998715565990975

In [ ]:
np.percentile(arr, 10)

0.0999713064230447

In [ ]:
(arr - np.mean(arr))/np.std(arr)

array([-0.01930606,  1.60760445, -0.95352001, ..., -0.16968066,
        0.1159597 , -0.37105922])

In [ ]:
arr1 = np.random.randint(50, 80, 100) # weight

In [ ]:
arr2 = np.random.randint(150, 185, 100) # heights

In [ ]:
arr3 = np.random.randint(17, 22, 100) # age

In [ ]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

# Pandas

In [ ]:
import numpy as np
import pandas as pd

## Creating Series Objects

In [ ]:
s = pd.Series([0, 1, 1, 2, 3, 5, 8])

In [ ]:
print(s)

0    0
1    1
2    1
3    2
4    3
5    5
6    8
dtype: int64


In [ ]:
s = pd.Series([0.0, 1, 1, 2, 3, 5, 8])

In [ ]:
print(s)

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    5.0
6    8.0
dtype: float64


In [ ]:
s.values

array([0., 1., 1., 2., 3., 5., 8.])

In [ ]:
for v in s.values:
    print(v)

0.0
1.0
1.0
2.0
3.0
5.0
8.0


In [ ]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=['mass', 'diameter', 'dayLength'])

In [ ]:
print(mercury)

mass            0.33
diameter       57.90
dayLength    4222.60
dtype: float64


In [ ]:
mercury['mass']

0.33

In [ ]:
mercury['dayLength']

4222.6

In [ ]:
mercury.mass

0.33

## Simple operations

In [ ]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146], 
                 index=['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])

In [ ]:
print(mass)

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Pluto         0.0146
dtype: float64


In [ ]:
mass[1]

4.87

In [ ]:
mass['Earth']

5.97

In [ ]:
mass['Earth': 'Jupiter']

Earth         5.970
Mars          0.642
Jupiter    1898.000
dtype: float64

In [ ]:
mass[2:5]

Earth         5.970
Mars          0.642
Jupiter    1898.000
dtype: float64

In [ ]:
mass > 100

Mercury    False
Venus      False
Earth      False
Mars       False
Jupiter     True
Saturn      True
Uranus     False
Neptune     True
Pluto      False
dtype: bool

In [ ]:
mass[mass > 100]

Jupiter    1898.0
Saturn      568.0
Neptune     102.0
dtype: float64

In [ ]:
np.mean(mass)

296.29184444444445

In [ ]:
np.median(mass)

5.97

## case-study

In [ ]:
nifty = pd.read_csv('Pyref.csv', index_col=0)

In [ ]:
nifty

Sales  Order ID
Index                    
1          2.25     87651
2          2.77     88726
3          3.07     88404
4          3.08     89595
5          3.13     86536
6          3.42     87464
7      13121.07     87993
8      13546.94     28001
9      20552.55     85938
10     27587.55     37924
11     29718.53     50656
12     31670.60      6562
13     43046.20      2433
14     45737.33      3841

In [ ]:
nifty.head(7)

Sales  Order ID
Index                    
1          2.25     87651
2          2.77     88726
3          3.07     88404
4          3.08     89595
5          3.13     86536
6          3.42     87464
7      13121.07     87993

In [ ]:
nifty.tail(7)

Sales  Order ID
Index                    
8      13546.94     28001
9      20552.55     85938
10     27587.55     37924
11     29718.53     50656
12     31670.60      6562
13     43046.20      2433
14     45737.33      3841

In [ ]:
np.mean(nifty)

Sales       16071.320714
Order ID    59408.857143
dtype: float64

In [ ]:
np.median(nifty)

28859.765

In [ ]:
np.std(nifty)

Sales       16375.583016
Order ID    34953.384295
dtype: float64

In [ ]:
nifty[1:]

Sales  Order ID
Index                    
2          2.77     88726
3          3.07     88404
4          3.08     89595
5          3.13     86536
6          3.42     87464
7      13121.07     87993
8      13546.94     28001
9      20552.55     85938
10     27587.55     37924
11     29718.53     50656
12     31670.60      6562
13     43046.20      2433
14     45737.33      3841

In [ ]:
nifty[:-1]

Sales  Order ID
Index                    
1          2.25     87651
2          2.77     88726
3          3.07     88404
4          3.08     89595
5          3.13     86536
6          3.42     87464
7      13121.07     87993
8      13546.94     28001
9      20552.55     85938
10     27587.55     37924
11     29718.53     50656
12     31670.60      6562
13     43046.20      2433